//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdeShawerma.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GdeShawerma.Core.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка получения ближайшей шавермы.
        /// </summary>
        internal static string ErrorNearby {
            get {
                return ResourceManager.GetString("ErrorNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы найти ближайшие заведения, пожалуйста отправтье вашу геопозицию, сделать это можно с помощью кнопки ниже.
        /// </summary>
        internal static string GdeResponse {
            get {
                return ResourceManager.GetString("GdeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотрите новые сообщения от бота.
        /// </summary>
        internal static string LookNewMessages {
            get {
                return ResourceManager.GetString("LookNewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее в приложении.
        /// </summary>
        internal static string More_app {
            get {
                return ResourceManager.GetString("More_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее в боте.
        /// </summary>
        internal static string More_bot {
            get {
                return ResourceManager.GetString("More_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рядом с вами заведений нет :(.
        /// </summary>
        internal static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы повторить отправьте команду 
        ////gde.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить геопозицию.
        /// </summary>
        internal static string ShareGeo {
            get {
                return ResourceManager.GetString("ShareGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, я бот Где Шаверма, и я покажу вам десять ближайших заведений с божественными свитками.
        ///Чтобы начать отправьте /gde
        ///
        ///Бот использует API приложения Где Шаверма
        ///[Android](https://play.google.com/store/apps/details?id=ru.gdeshaverma.android) [iOS](https://apps.apple.com/ru/app/%D0%B3%D0%B4%D0%B5-%D1%88%D0%B0%D0%B2%D0%B5%D1%80%D0%BC%D0%B0-%D0%BD%D0%B0%D0%B9%D0%B4%D0%B8-%D0%B8-%D1%81%D1%8A%D0%B5%D1%88%D1%8C/id1141097185)
        ///
        ///Разработчик @TarasBulba.
        /// </summary>
        internal static string StartResponse {
            get {
                return ResourceManager.GetString("StartResponse", resourceCulture);
            }
        }
    }
}
